Areas/Admin/Controllers/LessonsController.cs
using AIDL.Areas.Admin.Service;
using AIDL.Repository;
using AIDL.Shared.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AIDL.Areas.Admin.Controllers
{
    public class LessonsController : BaseController
    {
        private readonly LessonsService _lessonsService;
        public LessonsController()
        {
            _lessonsService = new LessonsService();
        }
        // GET: Admin/Lessonss
        public ActionResult Index()
        {
            return View(unitOfWork.tblLessonsRepo.GetAll().AsEnumerable());
        }

        [HttpGet]
        public ActionResult Add(int? Id)
        {
            tblLessons lesson = new tblLessons();
            if ((Id ?? 0) != 0)
            {
                lesson = unitOfWork.tblLessonsRepo.Get(Id ?? 0);
            }
            return View(lesson);
        }
        [HttpPost]
        public ActionResult Add(tblLessons lesson)
        {
            if (ModelState.IsValid)
            {
                _lessonsService.lesson = lesson;
                _lessonsService.AddEditLesson();
                MessageTempData = _lessonsService.Message;
                return RedirectToAction("Index");
            }
            MessageViewBag = "One or more error has been occured. Please contact customer care.";
            return View();
        }

        
    }
}

Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AIDL.Repository;
using AIDL.Service;
using AIDL.Shared.Service;
using AIDL.Models;
namespace AIDL.Controllers
{
    public class LessonsController : BaseController
    {
        LessonService lessonService = new LessonService();
        // GET: Lessons
        public ActionResult Index(string language, int? id)
        {  
            ViewBag.Title = clsUtils.FirstCharToUpper(language) + " Lessons";
            ViewBag.Language = clsUtils.FirstCharToUpper(language) ;
            tblLessons lesson = new tblLessons();
            LessonModel lessonModel = new LessonModel();
            PagedList.IPagedList<tblLessons> pageList = null;
            if (clsAuthentication.IsAuthenticated)
            {
                lesson = lessonService.getLesson(language.ToEnum<Enums.LessonLanguages>(), id);
                if (lesson != null)
                {
                    lessonModel.id = lesson.Id;
                    lessonModel.title = $"Page No. {lesson.page_number}" + ((lesson.page_part ?? 0) == 0 ? "" : $" - Part {lesson.page_part}");
                    lessonModel.audio = $"/Uploads/{language}/audio/{lesson.audio}";
                    lessonModel.image = $"/Uploads/{language}/image/{lesson.image}";
                    ViewBag.PageList = lessonService.geneatePagelist(language.ToEnum<Enums.LessonLanguages>(), (id ?? 1));
                }

            }
            if (lessonModel.id == 0)
            {
                lessonModel.id = 0;
                lessonModel.title = "Sample Page No. 22";
                lessonModel.audio = "/Uploads/Punjabi/audio/sample-page-22.mp4";
                lessonModel.image = "/Uploads/Punjabi/image/sample-page-22.jpg";
            }

            return View(lessonModel);
        }

        private void generatePagination(string lesson)
        {

        }

    }
}

Areas/Admin/Views/Lessons/Add.cshtml
@model AIDL.Repository.tblLessons
@{
    ViewBag.Title = "Add";
}

@Html.HiddenFor(x => x.Id)
@{
    ViewBag.title = "Add Lesson";
}
@section BoxHeader{
    <h3 class="box-title"> Add/Edit Lesson </h3>
    <a href='@Url.Action("Index", "Lessons")' class="btn btn-xs btn-primary pull-right"><i class="fa fa-eye" aria-hidden="true"> Manage Lessons</i></a>
}
@using (Html.BeginForm("Add", "Lessons", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    
    @Html.HiddenFor(model => model.Id)
    <div class="box-body">
        <div class="row">

            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-sm-2 control-label">Lesson Type</label>
                    <div class="col-sm-10">
                        @Html.DropDownList("LessonType", EnumHelper.GetSelectList(typeof(Enums.LessonLanguages)), null, new { @class = "form-control", @name = "lesson_type" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Page Number</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(x => x.page_number, new { @type = "text", @maxlength = "50", @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.page_number, null, new { @class = "error" })
                        <small>If only one page then 1 else if you want to add multiple pages then 1-5.</small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label">Page Part</label>
                    <div class="col-sm-10">
                        <select class="form-control" id="page_part" name="page_part">
                            <option value="0">None</option>
                            <option value="1">Part 1</option>
                            <option value="2">Part 2</option>
                            <option value="3">Part 3</option>
                            <option value="4">Part 4</option>
                            <option value="5">Part 5</option>
                            <option value="6">Part 6</option>
                            <option value="7">Part 7</option>
                            <option value="8">Part 8</option>
                            <option value="9">Part 9</option>
                            <option value="10">Part 10</option>
                        </select>
                        <small>If one page have multiple parts other wise leave it none.</small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Chapter</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="chapter" id="chapter">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                        </select>
                        @Html.ValidationMessageFor(x => x.chapter, null, new { @class = "error" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Lesson Audio</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(x => x.audio_file, new { @type = "file", @class = "form-control", @accept = "video/*, audio/*" })
                        @Html.ValidationMessageFor(x => x.audio_file, null, new { @class = "error" })
                        @if (!string.IsNullOrEmpty(Model.audio))
                        {
                            <a href="@AIDL.Shared.Service.clsUtils.GetAudioFilePath(Model.audio, Model.lesson_type)" target="_blank">Preview (" @Model.audio ")</a>
                        }
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Lesson Image</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(x => x.image_file, new { @type = "file", @class = "form-control", @accept = "image/*" })
                        @Html.ValidationMessageFor(x => x.image_file, null, new { @class = "error" })
                        @if (!string.IsNullOrEmpty(Model.image))
                        {
                            <a href="@AIDL.Shared.Service.clsUtils.GetImageFilePath(Model.image,Model.lesson_type)" target="_blank">Preview (" @Model.image ")</a>
                        }
                    </div>
                </div>
            </div>


        </div>
    </div>

    <div class="box-footer">
        <center>
            <input type="submit" class="btn btn-success" value="Submit" />
            <a href='@Url.Action("Index")' class="btn btn-danger">Cancel</a>
        </center>
    </div>
    @section Scripts{
        <script type="text/javascript">
        $(function () {
            if (@Model.Id != 0) {
                $('#page_part').val('@Model.page_part');
                $('#chapter').val('@Model.chapter');
            }
        });
        </script>
    }

}

Areas/Admin/Views/Lessons/Index.cshtml
@model IEnumerable<AIDL.Repository.tblLessons>
@{
    ViewBag.Title = "Manage Lessons";
}
@section BoxHeader{
    <h3 class="box-title">Manage Lessons</h3>
    <a href='@Url.Action("Add", "Lessons")' class="btn btn-xs btn-primary pull-right"><i class="fa fa-plus" aria-hidden="true"> Add Lesson</i></a>
}
<div class="box-body">
    <div class="row">
        <div class="col-md-12">
            <table id="datatable" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Lesson Type</th>
                        <th>Page Number</th>
                        <th>Page Part</th>
                        <th>Lesson Audio</th>
                        <th>Lesson Image</th>
                        <th>Created On</th>
                        <th>Modified On</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                    <tr>
                        <td>@Enums.GetLessonLanguages(item.lesson_type)</td>
                        <td>@item.page_number</td>
                        <td>@item.page_part</td>
                        <td><a href="@AIDL.Shared.Service.clsUtils.GetAudioFilePath(item.audio, item.lesson_type)" target="_blank">Preview (" @item.audio ")</a></td>
                        <td><a href="@AIDL.Shared.Service.clsUtils.GetImageFilePath(item.image,item.lesson_type)" target="_blank">Preview (" @item.image ")</a></td>
                        <td>@Html.FormatDateTime(item.created_on)</td>
                        <td>@Html.FormatDateTime(item.modified_on)</td>
                        <td><a href="#"><span id='@("spanStatus"+item.Id)' class="label @(item.status == true ? "label-success" : "label-danger")">@(item.status == true ? "Active" : "InActive")</span></a></td>
                        <td><a href="/admin/Lessons/add/@item.Id" title="Edit Lesson" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>&nbsp;</a></td>
                    </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>