Areas/Admin/Controllers/LoginController.cs
using AIDL.Areas.Admin.Shared.Service;
using AIDL.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace AIDL.Areas.Admin.Controllers
{
    public class LoginController : BaseController
    {
        // GET: Admin/Login
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("Admin") || User.IsInRole("Staff"))
                {
                    FormsIdentity fi;
                    fi = (FormsIdentity)User.Identity;
                    string[] ud = fi.Ticket.UserData.Split(';');
                    Session["AdminRole"] = ud[0];
                    Session["AdminId"] = Convert.ToInt32((string.IsNullOrEmpty(ud[1]) ? "0" : ud[1]));
                    Session["AdminUsername"] = ud[2];
                    Session["AdminName"] = ud[3];
                    return RedirectToAction("Index", "Home");
                }
            }
            if (Request.QueryString["returnUrl"] != null)
            {
                TempData["retUrl"] = Request.QueryString["returnUrl"].ToString();
            }

            return View();
        }

        [HttpPost]
        public ActionResult Index(tblAdminUsers objAdminUser)
        {
            var AdminUser = unitOfWork.tblAdminUsersRepo.FindBy(x => x.username == objAdminUser.username && x.password == objAdminUser.password && x.status == true).Select(x => x).FirstOrDefault();
            if (AdminUser != null)
            {
                if (AdminUser.password == objAdminUser.password)
                {
                    HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
                    if (cookie == null)
                    {
                        cookie = new HttpCookie(FormsAuthentication.FormsCookieName);

                        HttpContext.Response.Cookies.Add(cookie);
                    }
                    string UserData = AdminUser.role + ";" + AdminUser.Id + ";" + AdminUser.username + ";" + AdminUser.name;
                    string UserName = AdminUser.username;
                    FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, UserName, DateTime.Now, DateTime.Now.AddDays(1), true, UserData, FormsAuthentication.FormsCookiePath);
                    cookie.Value = FormsAuthentication.Encrypt(ticket);
                    cookie.Expires = DateTime.Now.AddDays(1);
                    HttpContext.Response.Cookies.Set(cookie);
                    HttpContext.User = new GenericPrincipal(HttpContext.User.Identity, UserData.Split(';'));
                    if (TempData["retUrl"] != null)
                    {
                        Response.Redirect(TempData["retUrl"].ToString(), true);
                    }
                    else
                        Response.Redirect("~/Admin/", true);
                }
                else
                {
                    MessageViewBag = "showMessage('Invalid username or password!',false);";
                }
            }   
            else
            {
                MessageViewBag = "showMessage('Invalid username or password!',false);";
            }
            return View();
        }

        public void SignOut()
        {
            Session.Abandon();
            FormsAuthentication.SignOut();
            Response.Redirect("~/Admin/Login", true);
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AIDL.Models;
using AIDL.Repository;
using AIDL.Service;
using AIDL.Shared.Service;

namespace AIDL.Controllers
{
    public class LoginController : BaseController
    {
        UserService userService = new UserService();
        // GET: Login
        public ActionResult Index()
        {
            UserLogin userLogin = new UserLogin();

            if (Request.Cookies["..."] != null)
            {
                string e = Request.Cookies["..."].Values["email"].ToDecrypt();
                string p = Request.Cookies["..."].Values["password"].ToDecrypt();
                userLogin.email = e;
                userLogin.password = p;
            }
            return View(userLogin);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UserLogin user)
        {
            tblUsers loggedInUser = new tblUsers();
            userService.userLoginModel = user;
            try
            {
                loggedInUser = userService.LoginUser();
                if (!userService.IsSuccess)
                {
                    MessageViewBag = userService.Message;
                }
                else
                {
                    return createCookieAndRedirectToUserHome(loggedInUser, user.RememberMe);
                }
            }
            catch (Exception ex)
            {
                MessageViewBag = ex.Message.ToExceptionError();
            }
            return View();
        }
        private ActionResult createCookieAndRedirectToUserHome(tblUsers user, bool rememberMe)
        {
            try
            {
                if (rememberMe)
                {
                    HttpContext.Request.Cookies.Remove("...");
                    HttpCookie Cookie = new HttpCookie("...");
                    Cookie.Values.Add("email", user.email.ToEncrypt());
                    Cookie.Values.Add("password", user.password.ToEncrypt());
                    Cookie.Expires = DateTime.Now.AddDays(365);
                    Response.Cookies.Add(Cookie);
                }
                HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
                if (cookie == null)
                {
                    cookie = new HttpCookie(FormsAuthentication.FormsCookieName);

                    HttpContext.Response.Cookies.Add(cookie);
                }
                string UserData = "User" + ";" + user.Id + ";" + user.name + ";" + user.email;
                string UserName = user.email;
                FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, UserName, DateTime.Now, DateTime.Now.AddDays(1), true, UserData, FormsAuthentication.FormsCookiePath);
                cookie.Value = FormsAuthentication.Encrypt(ticket);
                cookie.Expires = DateTime.Now.AddDays(30);
                HttpContext.Response.Cookies.Set(cookie);
                HttpContext.User = new GenericPrincipal(HttpContext.User.Identity, UserData.Split(';'));

                if (TempData["RetUrl"] != null)
                {
                    if (!Convert.ToString(TempData["RetUrl"]).Split('/').Last().ToLower().Contains("signout"))
                        Response.Redirect(Convert.ToString(TempData["RetUrl"]), true);
                }
            }
            catch (Exception ex)
            {
                ex.Message.ToExceptionError();
            }
            return RedirectToAction("Index","Home");
        }

        [Authorize]
        public ActionResult LogOut()
        {
            clsAuthentication.SignOutUser();
            return RedirectToAction("Index", "Home");
        }

    }
}

Areas/Admin/Views/Login/Index.cshtml
@model AIDL.Repository.tblAdminUsers
@{
    ViewBag.Title = "Admin Log In | AIDL | Arora Italian Driving License";
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin Log In | AIDL | Arora Italian Driving License</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="~/Areas/Admin/css/preloadlayout.bundle.css" rel="stylesheet" async="async" />
    <link href="~/Areas/Admin/css/layout.bundle.min.css" rel="stylesheet" async="async" />
</head>
<body class="hold-transition login-page">
    <div id="div_msg" style="display: none;color:#0000FF;">
        <strong style="color:#3db714;"></strong>
    </div>
    <div class="login-box">
        <div class="login-logo">
            <a href="/."> <img src="@Url.Content("~/Content/img/logo.png")" alt="AIDL | Arora Italian Driving License"></a>
        </div>
        <!-- /.login-logo -->
        @using (Ajax.BeginForm("Index", "Login", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "login-box", AllowCache = true }))
        {
            @Html.ValidationSummary(true)
            <div class="login-box-body">
                <p class="login-box-msg">Sign in to start your session</p>
                <div class="form-group has-feedback">
                    @Html.TextBoxFor(model => model.username, new { @class = "form-control", placeholder = "Username" })
                    @Html.ValidationMessageFor(model => model.username, null, new { @class = "error" })
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    @Html.PasswordFor(model => model.password, new { @class = "form-control", placeholder = "Password" })
                    @Html.ValidationMessageFor(model => model.password, null, new { @class = "error" })
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.social-auth-links -->
            </div>
        }
        <!-- /.login-box-body -->
    </div>

</body>
</html>
<script src="~/Areas/Admin/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Areas/Admin/Scripts/jquery.validate.bundle.min.js"></script>
<script src="~/Areas/Admin/Scripts/layout.bundle.min.js"></script>
@Scripts.Render("~/bundles/Js_Developer")
<script type="text/javascript">
    $(function () {
        @Html.Raw(ViewBag.Msg)
    });
</script>